version: '3.7'

services:
  redis:
    image: redis:6.0
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flightsparser
    ports:
      - 5432:5432

volumes:
  postgres_data:
  